# Don't change this file, it's the default config file. Instead, please edit
# /etc/nodeftpd.yml

listen: '%default_ip%'
listenNat: '176.9.53.111'
umask: 022
port: 21
socket: /var/run/nodeftpd.sock
pid_file: /var/run/nodeftpd.pid
idle_workers: 5
logging:
  error_log: /var/log/nodeftpd/error.log
  access_log: /var/log/nodeftpd/access.log
passive_port_range: 40001-40010
motd: 'NodeFTPD %pkg.version% Server (%os.hostname%)'
auth:
  provider: mongodb
  default_chroot: '~'
  dsn: 'mongodb://mongodb:27017/lunchr'
tls:
  enabled: false
  key: ''
  cert: ''
  port: 990
